import { getRandomColor } from "../utils/GetRandomColor";

export const countryData = [
  { _id: 1, name: "Afghanistan", flag: "🇦🇫", code: "AF", dial_code: "+93" },
  { _id: 2, name: "Åland Islands", flag: "🇦🇽", code: "AX", dial_code: "+358" },
  { _id: 3, name: "Albania", flag: "🇦🇱", code: "AL", dial_code: "+355" },
  { _id: 4, name: "Algeria", flag: "🇩🇿", code: "DZ", dial_code: "+213" },
  { _id: 5, name: "American Samoa", flag: "🇦🇸", code: "AS", dial_code: "+1684" },
  { _id: 6, name: "Andorra", flag: "🇦🇩", code: "AD", dial_code: "+376" },
  { _id: 7, name: "Angola", flag: "🇦🇴", code: "AO", dial_code: "+244" },
  { _id: 8, name: "Anguilla", flag: "🇦🇮", code: "AI", dial_code: "+1264" },
  { _id: 9, name: "Antarctica", flag: "🇦🇶", code: "AQ", dial_code: "+672" },
  { _id: 10, name: "Antigua and Barbuda", flag: "🇦🇬", code: "AG", dial_code: "+1268" },
  { _id: 11, name: "Argentina", flag: "🇦🇷", code: "AR", dial_code: "+54" },
  { _id: 12, name: "Armenia", flag: "🇦🇲", code: "AM", dial_code: "+374" },
  { _id: 13, name: "Aruba", flag: "🇦🇼", code: "AW", dial_code: "+297" },
  { _id: 14, name: "Australia", flag: "🇦🇺", code: "AU", dial_code: "+61" },
  { _id: 15, name: "Austria", flag: "🇦🇹", code: "AT", dial_code: "+43" },
  { _id: 16, name: "Azerbaijan", flag: "🇦🇿", code: "AZ", dial_code: "+994" },
  { _id: 17, name: "Bahamas", flag: "🇧🇸", code: "BS", dial_code: "+1242" },
  { _id: 18, name: "Bahrain", flag: "🇧🇭", code: "BH", dial_code: "+973" },
  { _id: 19, name: "Bangladesh", flag: "🇧🇩", code: "BD", dial_code: "+880" },
  { _id: 20, name: "Barbados", flag: "🇧🇧", code: "BB", dial_code: "+1246" },
  { _id: 21, name: "Belarus", flag: "🇧🇾", code: "BY", dial_code: "+375" },
  { _id: 22, name: "Belgium", flag: "🇧🇪", code: "BE", dial_code: "+32" },
  { _id: 23, name: "Belize", flag: "🇧🇿", code: "BZ", dial_code: "+501" },
  { _id: 24, name: "Benin", flag: "🇧🇯", code: "BJ", dial_code: "+229" },
  { _id: 25, name: "Bermuda", flag: "🇧🇲", code: "BM", dial_code: "+1441" },
  { _id: 26, name: "Bhutan", flag: "🇧🇹", code: "BT", dial_code: "+975" },
  { _id: 27, name: "Bolivia, Plurinational State of bolivia", flag: "🇧🇴", code: "BO", dial_code: "+591" },
  { _id: 28, name: "Bosnia and Herzegovina", flag: "🇧🇦", code: "BA", dial_code: "+387" },
  { _id: 29, name: "Botswana", flag: "🇧🇼", code: "BW", dial_code: "+267" },
  { _id: 30, name: "Bouvet Island", flag: "🇧🇻", code: "BV", dial_code: "+47" },
  { _id: 31, name: "Brazil", flag: "🇧🇷", code: "BR", dial_code: "+55" },
  { _id: 32, name: "British Indian Ocean Territory", flag: "🇮🇴", code: "IO", dial_code: "+246" },
  { _id: 33, name: "Brunei Darussalam", flag: "🇧🇳", code: "BN", dial_code: "+673" },
  { _id: 34, name: "Bulgaria", flag: "🇧🇬", code: "BG", dial_code: "+359" },
  { _id: 35, name: "Burkina Faso", flag: "🇧🇫", code: "BF", dial_code: "+226" },
  { _id: 36, name: "Burundi", flag: "🇧🇮", code: "BI", dial_code: "+257" },
  { _id: 37, name: "Cambodia", flag: "🇰🇭", code: "KH", dial_code: "+855" },
  { _id: 38, name: "Cameroon", flag: "🇨🇲", code: "CM", dial_code: "+237" },
  { _id: 39, name: "Canada", flag: "🇨🇦", code: "CA", dial_code: "+1" },
  { _id: 40, name: "Cape Verde", flag: "🇨🇻", code: "CV", dial_code: "+238" },
  { _id: 41, name: "Cayman Islands", flag: "🇰🇾", code: "KY", dial_code: "+1345" },
  { _id: 42, name: "Central African Republic", flag: "🇨🇫", code: "CF", dial_code: "+236" },
  { _id: 43, name: "Chad", flag: "🇹🇩", code: "TD", dial_code: "+235" },
  { _id: 44, name: "Chile", flag: "🇨🇱", code: "CL", dial_code: "+56" },
  { _id: 45, name: "China", flag: "🇨🇳", code: "CN", dial_code: "+86" },
  { _id: 46, name: "Christmas Island", flag: "🇨🇽", code: "CX", dial_code: "+61" },
  { _id: 47, name: "Cocos (Keeling) Islands", flag: "🇨🇨", code: "CC", dial_code: "+61" },
  { _id: 48, name: "Colombia", flag: "🇨🇴", code: "CO", dial_code: "+57" },
  { _id: 49, name: "Comoros", flag: "🇰🇲", code: "KM", dial_code: "+269" },
  { _id: 50, name: "Congo", flag: "🇨🇬", code: "CG", dial_code: "+242" },
  { _id: 51, name: "Congo, The Democratic Republic of the Congo", flag: "🇨🇩", code: "CD", dial_code: "+243" },
  { _id: 52, name: "Cook Islands", flag: "🇨🇰", code: "CK", dial_code: "+682" },
  { _id: 53, name: "Costa Rica", flag: "🇨🇷", code: "CR", dial_code: "+506" },
  { _id: 54, name: "Cote d'Ivoire", flag: "🇨🇮", code: "CI", dial_code: "+225" },
  { _id: 55, name: "Croatia", flag: "🇭🇷", code: "HR", dial_code: "+385" },
  { _id: 56, name: "Cuba", flag: "🇨🇺", code: "CU", dial_code: "+53" },
  { _id: 57, name: "Cyprus", flag: "🇨🇾", code: "CY", dial_code: "+357" },
  { _id: 58, name: "Czech Republic", flag: "🇨🇿", code: "CZ", dial_code: "+420" },
  { _id: 59, name: "Denmark", flag: "🇩🇰", code: "DK", dial_code: "+45" },
  { _id: 60, name: "Djibouti", flag: "🇩🇯", code: "DJ", dial_code: "+253" },
  { _id: 61, name: "Dominica", flag: "🇩🇲", code: "DM", dial_code: "+1767" },
  { _id: 62, name: "Dominican Republic", flag: "🇩🇴", code: "DO", dial_code: "+1849" },
  { _id: 63, name: "Ecuador", flag: "🇪🇨", code: "EC", dial_code: "+593" },
  { _id: 64, name: "Egypt", flag: "🇪🇬", code: "EG", dial_code: "+20" },
  { _id: 65, name: "El Salvador", flag: "🇸🇻", code: "SV", dial_code: "+503" },
  { _id: 66, name: "Equatorial Guinea", flag: "🇬🇶", code: "GQ", dial_code: "+240" },
  { _id: 67, name: "Eritrea", flag: "🇪🇷", code: "ER", dial_code: "+291" },
  { _id: 68, name: "Estonia", flag: "🇪🇪", code: "EE", dial_code: "+372" },
  { _id: 69, name: "Ethiopia", flag: "🇪🇹", code: "ET", dial_code: "+251" },
  { _id: 70, name: "Falkland Islands (Malvinas)", flag: "🇫🇰", code: "FK", dial_code: "+500" },
  { _id: 71, name: "Faroe Islands", flag: "🇫🇴", code: "FO", dial_code: "+298" },
  { _id: 72, name: "Fiji", flag: "🇫🇯", code: "FJ", dial_code: "+679" },
  { _id: 73, name: "Finland", flag: "🇫🇮", code: "FI", dial_code: "+358" },
  { _id: 74, name: "France", flag: "🇫🇷", code: "FR", dial_code: "+33" },
  { _id: 75, name: "French Guiana", flag: "🇬🇫", code: "GF", dial_code: "+594" },
  { _id: 76, name: "French Polynesia", flag: "🇵🇫", code: "PF", dial_code: "+689" },
  { _id: 77, name: "French Southern Territories", flag: "🇹🇫", code: "TF", dial_code: "+262" },
  { _id: 78, name: "Gabon", flag: "🇬🇦", code: "GA", dial_code: "+241" },
  { _id: 79, name: "Gambia", flag: "🇬🇲", code: "GM", dial_code: "+220" },
  { _id: 80, name: "Georgia", flag: "🇬🇪", code: "GE", dial_code: "+995" },
  { _id: 81, name: "Germany", flag: "🇩🇪", code: "DE", dial_code: "+49" },
  { _id: 82, name: "Ghana", flag: "🇬🇭", code: "GH", dial_code: "+233" },
  { _id: 83, name: "Gibraltar", flag: "🇬🇮", code: "GI", dial_code: "+350" },
  { _id: 84, name: "Greece", flag: "🇬🇷", code: "GR", dial_code: "+30" },
  { _id: 85, name: "Greenland", flag: "🇬🇱", code: "GL", dial_code: "+299" },
  { _id: 86, name: "Grenada", flag: "🇬🇩", code: "GD", dial_code: "+1473" },
  { _id: 87, name: "Guadeloupe", flag: "🇬🇵", code: "GP", dial_code: "+590" },
  { _id: 88, name: "Guam", flag: "🇬🇺", code: "GU", dial_code: "+1671" },
  { _id: 89, name: "Guatemala", flag: "🇬🇹", code: "GT", dial_code: "+502" },
  { _id: 90, name: "Guernsey", flag: "🇬🇬", code: "GG", dial_code: "+44" },
  { _id: 91, name: "Guinea", flag: "🇬🇳", code: "GN", dial_code: "+224" },
  { _id: 92, name: "Guinea-Bissau", flag: "🇬🇼", code: "GW", dial_code: "+245" },
  { _id: 93, name: "Guyana", flag: "🇬🇾", code: "GY", dial_code: "+592" },
  { _id: 94, name: "Haiti", flag: "🇭🇹", code: "HT", dial_code: "+509" },
  { _id: 95, name: "Heard Island and Mcdonald Islands", flag: "🇭🇲", code: "HM", dial_code: "+672" },
  { _id: 96, name: "Holy See (Vatican City State)", flag: "🇻🇦", code: "VA", dial_code: "+379" },
  { _id: 97, name: "Honduras", flag: "🇭🇳", code: "HN", dial_code: "+504" },
  { _id: 98, name: "Hong Kong", flag: "🇭🇰", code: "HK", dial_code: "+852" },
  { _id: 99, name: "Hungary", flag: "🇭🇺", code: "HU", dial_code: "+36" },
  { _id: 100, name: "Iceland", flag: "🇮🇸", code: "IS", dial_code: "+354" },
  { _id: 101, name: "India", flag: "🇮🇳", code: "IN", dial_code: "+91" },
  { _id: 102, name: "Indonesia", flag: "🇮🇩", code: "ID", dial_code: "+62" },
  { _id: 103, name: "Iran, Islamic Republic of Persian Gulf", flag: "🇮🇷", code: "IR", dial_code: "+98" },
  { _id: 104, name: "Iraq", flag: "🇮🇶", code: "IQ", dial_code: "+964" },
  { _id: 105, name: "Ireland", flag: "🇮🇪", code: "IE", dial_code: "+353" },
  { _id: 106, name: "Isle of Man", flag: "🇮🇲", code: "IM", dial_code: "+44" },
  { _id: 107, name: "Israel", flag: "🇮🇱", code: "IL", dial_code: "+972" },
  { _id: 108, name: "Italy", flag: "🇮🇹", code: "IT", dial_code: "+39" },
  { _id: 109, name: "Jamaica", flag: "🇯🇲", code: "JM", dial_code: "+1876" },
  { _id: 110, name: "Japan", flag: "🇯🇵", code: "JP", dial_code: "+81" },
  { _id: 111, name: "Jersey", flag: "🇯🇪", code: "JE", dial_code: "+44" },
  { _id: 112, name: "Jordan", flag: "🇯🇴", code: "JO", dial_code: "+962" },
  { _id: 113, name: "Kazakhstan", flag: "🇰🇿", code: "KZ", dial_code: "+7" },
  { _id: 114, name: "Kenya", flag: "🇰🇪", code: "KE", dial_code: "+254" },
  { _id: 115, name: "Kiribati", flag: "🇰🇮", code: "KI", dial_code: "+686" },
  { _id: 116, name: "Korea, Democratic People's Republic of Korea", flag: "🇰🇵", code: "KP", dial_code: "+850" },
  { _id: 117, name: "Korea, Republic of South Korea", flag: "🇰🇷", code: "KR", dial_code: "+82" },
  { _id: 118, name: "Kuwait", flag: "🇰🇼", code: "KW", dial_code: "+965" },
  { _id: 119, name: "Kyrgyzstan", flag: "🇰🇬", code: "KG", dial_code: "+996" },
  { _id: 120, name: "Laos", flag: "🇱🇦", code: "LA", dial_code: "+856" },
  { _id: 121, name: "Latvia", flag: "🇱🇻", code: "LV", dial_code: "+371" },
  { _id: 122, name: "Lebanon", flag: "🇱🇧", code: "LB", dial_code: "+961" },
  { _id: 123, name: "Lesotho", flag: "🇱🇸", code: "LS", dial_code: "+266" },
  { _id: 124, name: "Liberia", flag: "🇱🇷", code: "LR", dial_code: "+231" },
  { _id: 125, name: "Libyan Arab Jamahiriya", flag: "🇱🇾", code: "LY", dial_code: "+218" },
  { _id: 126, name: "Liechtenstein", flag: "🇱🇮", code: "LI", dial_code: "+423" },
  { _id: 127, name: "Lithuania", flag: "🇱🇹", code: "LT", dial_code: "+370" },
  { _id: 128, name: "Luxembourg", flag: "🇱🇺", code: "LU", dial_code: "+352" },
  { _id: 129, name: "Macao", flag: "🇲🇴", code: "MO", dial_code: "+853" },
  { _id: 130, name: "Macedonia", flag: "🇲🇰", code: "MK", dial_code: "+389" },
  { _id: 131, name: "Madagascar", flag: "🇲🇬", code: "MG", dial_code: "+261" },
  { _id: 132, name: "Malawi", flag: "🇲🇼", code: "MW", dial_code: "+265" },
  { _id: 133, name: "Malaysia", flag: "🇲🇾", code: "MY", dial_code: "+60" },
  { _id: 134, name: "Maldives", flag: "🇲🇻", code: "MV", dial_code: "+960" },
  { _id: 135, name: "Mali", flag: "🇲🇱", code: "ML", dial_code: "+223" },
  { _id: 136, name: "Malta", flag: "🇲🇹", code: "MT", dial_code: "+356" },
  { _id: 137, name: "Marshall Islands", flag: "🇲🇭", code: "MH", dial_code: "+692" },
  { _id: 138, name: "Martinique", flag: "🇲🇶", code: "MQ", dial_code: "+596" },
  { _id: 139, name: "Mauritania", flag: "🇲🇷", code: "MR", dial_code: "+222" },
  { _id: 140, name: "Mauritius", flag: "🇲🇺", code: "MU", dial_code: "+230" },
  { _id: 141, name: "Mayotte", flag: "🇾🇹", code: "YT", dial_code: "+262" },
  { _id: 142, name: "Mexico", flag: "🇲🇽", code: "MX", dial_code: "+52" },
  { _id: 143, name: "Micronesia, Federated States of Micronesia", flag: "🇫🇲", code: "FM", dial_code: "+691" },
  { _id: 144, name: "Moldova", flag: "🇲🇩", code: "MD", dial_code: "+373" },
  { _id: 145, name: "Monaco", flag: "🇲🇨", code: "MC", dial_code: "+377" },
  { _id: 146, name: "Mongolia", flag: "🇲🇳", code: "MN", dial_code: "+976" },
  { _id: 147, name: "Montenegro", flag: "🇲🇪", code: "ME", dial_code: "+382" },
  { _id: 148, name: "Montserrat", flag: "🇲🇸", code: "MS", dial_code: "+1664" },
  { _id: 149, name: "Morocco", flag: "🇲🇦", code: "MA", dial_code: "+212" },
  { _id: 150, name: "Mozambique", flag: "🇲🇿", code: "MZ", dial_code: "+258" },
  { _id: 151, name: "Myanmar", flag: "🇲🇲", code: "MM", dial_code: "+95" },
  { _id: 152, name: "Namibia", flag: "🇳🇦", code: "NA", dial_code: "+264" },
  { _id: 153, name: "Nauru", flag: "🇳🇷", code: "NR", dial_code: "+674" },
  { _id: 154, name: "Nepal", flag: "🇳🇵", code: "NP", dial_code: "+977" },
  { _id: 155, name: "Netherlands", flag: "🇳🇱", code: "NL", dial_code: "+31" },
  { _id: 156, name: "Netherlands Antilles", flag: "🇳🇱", code: "AN", dial_code: "+599" },
  { _id: 157, name: "New Caledonia", flag: "🇳🇨", code: "NC", dial_code: "+687" },
  { _id: 158, name: "New Zealand", flag: "🇳🇿", code: "NZ", dial_code: "+64" },
  { _id: 159, name: "Nicaragua", flag: "🇳🇮", code: "NI", dial_code: "+505" },
  { _id: 160, name: "Niger", flag: "🇳🇪", code: "NE", dial_code: "+227" },
  { _id: 161, name: "Nigeria", flag: "🇳🇬", code: "NG", dial_code: "+234" },
  { _id: 162, name: "Niue", flag: "🇳🇺", code: "NU", dial_code: "+683" },
  { _id: 163, name: "Norfolk Island", flag: "🇳🇫", code: "NF", dial_code: "+672" },
  { _id: 164, name: "Northern Mariana Islands", flag: "🇲🇵", code: "MP", dial_code: "+1670" },
  { _id: 165, name: "Norway", flag: "🇳🇴", code: "NO", dial_code: "+47" },
  { _id: 166, name: "Oman", flag: "🇴🇲", code: "OM", dial_code: "+968" },
  { _id: 167, name: "Pakistan", flag: "🇵🇰", code: "PK", dial_code: "+92" },
  { _id: 168, name: "Palau", flag: "🇵🇼", code: "PW", dial_code: "+680" },
  { _id: 169, name: "Palestinian Territory, Occupied", flag: "🇵🇸", code: "PS", dial_code: "+970" },
  { _id: 170, name: "Panama", flag: "🇵🇦", code: "PA", dial_code: "+507" },
  { _id: 171, name: "Papua New Guinea", flag: "🇵🇬", code: "PG", dial_code: "+675" },
  { _id: 172, name: "Paraguay", flag: "🇵🇾", code: "PY", dial_code: "+595" },
  { _id: 173, name: "Peru", flag: "🇵🇪", code: "PE", dial_code: "+51" },
  { _id: 174, name: "Philippines", flag: "🇵🇭", code: "PH", dial_code: "+63" },
  { _id: 175, name: "Pitcairn", flag: "🇵🇳", code: "PN", dial_code: "+64" },
  { _id: 176, name: "Poland", flag: "🇵🇱", code: "PL", dial_code: "+48" },
  { _id: 177, name: "Portugal", flag: "🇵🇹", code: "PT", dial_code: "+351" },
  { _id: 178, name: "Puerto Rico", flag: "🇵🇷", code: "PR", dial_code: "+1939" },
  { _id: 179, name: "Qatar", flag: "🇶🇦", code: "QA", dial_code: "+974" },
  { _id: 180, name: "Romania", flag: "🇷🇴", code: "RO", dial_code: "+40" },
  { _id: 181, name: "Russia", flag: "🇷🇺", code: "RU", dial_code: "+7" },
  { _id: 182, name: "Rwanda", flag: "🇷🇼", code: "RW", dial_code: "+250" },
  { _id: 183, name: "Reunion", flag: "🇷🇪", code: "RE", dial_code: "+262" },
  { _id: 184, name: "Saint Barthelemy", flag: "🇧🇱", code: "BL", dial_code: "+590" },
  { _id: 185, name: "Saint Helena, Ascension and Tristan Da Cunha", flag: "🇸🇭", code: "SH", dial_code: "+290" },
  { _id: 186, name: "Saint Kitts and Nevis", flag: "🇰🇳", code: "KN", dial_code: "+1869" },
  { _id: 187, name: "Saint Lucia", flag: "🇱🇨", code: "LC", dial_code: "+1758" },
  { _id: 188, name: "Saint Martin", flag: "🇲🇫", code: "MF", dial_code: "+590" },
  { _id: 189, name: "Saint Pierre and Miquelon", flag: "🇵🇲", code: "PM", dial_code: "+508" },
  { _id: 190, name: "Saint Vincent and the Grenadines", flag: "🇻🇨", code: "VC", dial_code: "+1784" },
  { _id: 191, name: "Samoa", flag: "🇼🇸", code: "WS", dial_code: "+685" },
  { _id: 192, name: "San Marino", flag: "🇸🇲", code: "SM", dial_code: "+378" },
  { _id: 193, name: "Sao Tome and Principe", flag: "🇸🇹", code: "ST", dial_code: "+239" },
  { _id: 194, name: "Saudi Arabia", flag: "🇸🇦", code: "SA", dial_code: "+966" },
  { _id: 195, name: "Senegal", flag: "🇸🇳", code: "SN", dial_code: "+221" },
  { _id: 196, name: "Serbia", flag: "🇷🇸", code: "RS", dial_code: "+381" },
  { _id: 197, name: "Seychelles", flag: "🇸🇨", code: "SC", dial_code: "+248" },
  { _id: 198, name: "Sierra Leone", flag: "🇸🇱", code: "SL", dial_code: "+232" },
  { _id: 199, name: "Singapore", flag: "🇸🇬", code: "SG", dial_code: "+65" },
  { _id: 200, name: "Slovakia", flag: "🇸🇰", code: "SK", dial_code: "+421" },
  { _id: 201, name: "Slovenia", flag: "🇸🇮", code: "SI", dial_code: "+386" },
  { _id: 202, name: "Solomon Islands", flag: "🇸🇧", code: "SB", dial_code: "+677" },
  { _id: 203, name: "Somalia", flag: "🇸🇴", code: "SO", dial_code: "+252" },
  { _id: 204, name: "South Africa", flag: "🇿🇦", code: "ZA", dial_code: "+27" },
  { _id: 205, name: "South Sudan", flag: "🇸🇸", code: "SS", dial_code: "+211" },
  { _id: 206, name: "South Georgia and the South Sandwich Islands", flag: "🇬🇸", code: "GS", dial_code: "+500" },
  { _id: 207, name: "Spain", flag: "🇪🇸", code: "ES", dial_code: "+34" },
  { _id: 208, name: "Sri Lanka", flag: "🇱🇰", code: "LK", dial_code: "+94" },
  { _id: 209, name: "Sudan", flag: "🇸🇩", code: "SD", dial_code: "+249" },
  { _id: 210, name: "Suriname", flag: "🇸🇷", code: "SR", dial_code: "+597" },
  { _id: 211, name: "Svalbard and Jan Mayen", flag: "🇸🇯", code: "SJ", dial_code: "+47" },
  { _id: 212, name: "Swaziland", flag: "🇸🇿", code: "SZ", dial_code: "+268" },
  { _id: 213, name: "Sweden", flag: "🇸🇪", code: "SE", dial_code: "+46" },
  { _id: 214, name: "Switzerland", flag: "🇨🇭", code: "CH", dial_code: "+41" },
  { _id: 215, name: "Syrian Arab Republic", flag: "🇸🇾", code: "SY", dial_code: "+963" },
  { _id: 216, name: "Taiwan", flag: "🇹🇼", code: "TW", dial_code: "+886" },
  { _id: 217, name: "Tajikistan", flag: "🇹🇯", code: "TJ", dial_code: "+992" },
  { _id: 218, name: "Tanzania, United Republic of Tanzania", flag: "🇹🇿", code: "TZ", dial_code: "+255" },
  { _id: 219, name: "Thailand", flag: "🇹🇭", code: "TH", dial_code: "+66" },
  { _id: 220, name: "Timor-Leste", flag: "🇹🇱", code: "TL", dial_code: "+670" },
  { _id: 221, name: "Togo", flag: "🇹🇬", code: "TG", dial_code: "+228" },
  { _id: 222, name: "Tokelau", flag: "🇹🇰", code: "TK", dial_code: "+690" },
  { _id: 223, name: "Tonga", flag: "🇹🇴", code: "TO", dial_code: "+676" },
  { _id: 224, name: "Trinidad and Tobago", flag: "🇹🇹", code: "TT", dial_code: "+1868" },
  { _id: 225, name: "Tunisia", flag: "🇹🇳", code: "TN", dial_code: "+216" },
  { _id: 226, name: "Turkey", flag: "🇹🇷", code: "TR", dial_code: "+90" },
  { _id: 227, name: "Turkmenistan", flag: "🇹🇲", code: "TM", dial_code: "+993" },
  { _id: 228, name: "Turks and Caicos Islands", flag: "🇹🇨", code: "TC", dial_code: "+1649" },
  { _id: 229, name: "Tuvalu", flag: "🇹🇻", code: "TV", dial_code: "+688" },
  { _id: 230, name: "Uganda", flag: "🇺🇬", code: "UG", dial_code: "+256" },
  { _id: 231, name: "Ukraine", flag: "🇺🇦", code: "UA", dial_code: "+380" },
  { _id: 232, name: "United Arab Emirates", flag: "🇦🇪", code: "AE", dial_code: "+971" },
  { _id: 233, name: "United Kingdom", flag: "🇬🇧", code: "GB", dial_code: "+44" },
  { _id: 234, name: "United States", flag: "🇺🇸", code: "US", dial_code: "+1" },
  { _id: 235, name: "Uruguay", flag: "🇺🇾", code: "UY", dial_code: "+598" },
  { _id: 236, name: "Uzbekistan", flag: "🇺🇿", code: "UZ", dial_code: "+998" },
  { _id: 237, name: "Vanuatu", flag: "🇻🇺", code: "VU", dial_code: "+678" },
  { _id: 238, name: "Venezuela, Bolivarian Republic of Venezuela", flag: "🇻🇪", code: "VE", dial_code: "+58" },
  { _id: 239, name: "Vietnam", flag: "🇻🇳", code: "VN", dial_code: "+84" },
  { _id: 240, name: "Virgin Islands, British", flag: "🇻🇬", code: "VG", dial_code: "+1284" },
  { _id: 241, name: "Virgin Islands, U.S.", flag: "🇻🇮", code: "VI", dial_code: "+1340" },
  { _id: 242, name: "Wallis and Futuna", flag: "🇼🇫", code: "WF", dial_code: "+681" },
  { _id: 243, name: "Yemen", flag: "🇾🇪", code: "YE", dial_code: "+967" },
  { _id: 244, name: "Zambia", flag: "🇿🇲", code: "ZM", dial_code: "+260" },
  { _id: 245, name: "Zimbabwe", flag: "🇿🇼", code: "ZW", dial_code: "+263" }
];

export const listData = [
    {
      _id: 1,
      address: '1 Bag End, Hobbiton Westfarthing, The Shire',
      houseNum: 1,
      color: getRandomColor(),
      region: {latitude: 37.78825, longitude: -122.4324},
    },
    {
      _id: 2,
      address: '1 Wending Way, Hobbiton Westfarthing, The Shire',
      houseNum: 2,
      color: getRandomColor(),
      region: {latitude: 37.779384, longitude: -122.426088},
    },
    {
      _id: 3,
      address: '2 Harrow Road, Hobbiton Westfarthing, The Shire',
      houseNum: 3,
      color: getRandomColor(),
      region: {latitude: 37.780376, longitude: -122.443867},
    },
    {
      _id: 4,
      address: '1 Pleasant Street, Hobbiton Westfarthing, The Shire',
      houseNum: 4,
      color: getRandomColor(),
      region: {latitude: 37.7836821, longitude: -122.4462204},
    }
];

export const totalVotersData = [
  {
    _id: 1,
    name: 'Ailbo Baggins',
    sex: 'F',
    address: '1 Bag End, The Shire, Middle Earth',
    age: 102,
    partyCode: 'Independent',
  },
  {
    _id: 2,
    name: 'Zilbo Baggins',
    sex: 'F',
    address: '1 Bag End, The Shire, Middle Earth',
    age: 45,
    partyCode: 'Republican',
  },
  {
    _id: 3,
    name: 'Bilbo Baggins',
    sex: 'F',
    address: '1 Bag End, The Shire, Middle Earth',
    age: 32,
    partyCode: 'Republican',
  },
  {
    _id: 4,
    name: 'Samwise Gamgee',
    sex: 'M',
    address: '1 Bag End, The Shire, Middle Earth',
    age: 42,
    partyCode: 'Republican',
  },
];

export const contactedData = [
  { _id: 1, title: 'In Person', desc: 'Spoke with (Insert Name) in person' },
  { _id: 2, title: 'By Phone', desc: 'Spoke with (Insert Name) by phone call' },
  { _id: 3, title: 'By Text', desc: 'Spoke with (Insert Name) by text message' },
  { _id: 4, title: 'By Email', desc: 'Spoke with (Insert Name) by email' },
  { _id: 5, title: 'While Canvassing', desc: 'Spoke with (Insert Name) while canvassing' },
  { _id: 6, title: 'Over Social Media', desc: 'Spoke with (Insert Name) over social media' },
];

export const districtList = [
  {
    _id: 1,
    title: 'District 1 Canvassing 55+ - 001',
    num: 4
  },
  {
    _id: 2,
    title: 'District 1 Canvassing 55+ - 002',
    num: 50
  },
  {
    _id: 3,
    title: 'District 1 Canvassing 55+ - 003',
    num: 60
  },
];

export const canvassListButtons = [
  {_id: 1, title: 'List'}, 
  {_id: 2, title: 'Map'}
];

export const voterCheckbuttons = [
  {_id: 1, name: 'Wrong number', type: 'wrong'},
  {_id: 2, name: 'Do Not Call', type: 'donot'},
  {_id: 3, name: 'Contact Later', type: 'contact'},
  {_id: 4, name: 'Survey', type: 'survey'},
];

export const canvassMapDetailsButtons = [
  {_id: 1, name: 'Refused', type: 'wrong'},
  {_id: 2, name: 'Restriced Access', type: 'donot'},
  {_id: 3, name: 'No one home', type: 'contact'},
  {_id: 4, name: 'Literature Drop', type: 'survey'},
];

export const canvasSearchFilters = [
  {_id: 1, name: 'Un Select', field: 'UN SELECT'},
  {_id: 2, name: 'Address', field: 'ADDRESS'},
  {_id: 3, name: 'City', field: 'CITY'},
  {_id: 4, name: 'State', field: 'STATE'},
  {_id: 5, name: 'Country', field: 'AI_COUNTY_NAME'},
]


export const script = `"Hi! my name _____ and I am here on befalf of Hanna Jacobs for Congress, Are you available for breif coversation?"`;